### ISSUE TITLE
JSON doc size

### ISSUE THREAD

**Issue by barrj4** [Cimera42/esp-discord-client#20]
I had initially got this working on my own server but was struggling to get it going on other servers. Realized that the JSON doc size was too small for servers where there is a list of permissions in the msg. 

The extra length cut off the channel_id and caused the channel_id to always be null. Increasing the doc size to 2048 seems to work okay.

**Comment by Cimera42** [comment]
Hi @barrj4, thanks for the report.

I've added handling for the error returned by ArduinoJSON here: https://github.com/Cimera42/esp-discord-client/pull/22
With that change, you should now get an actual error that there was insufficient memory allocated to deserialise the JSON.

I've also increased the default size of the JSON doc: https://github.com/Cimera42/esp-discord-client/pull/24

Cheers.
